// ============================================================
// Mock Data for Local Civic-Engagement Hub
// ============================================================

export const MOCK_USERS = [
  { user_id: 'u1', phone_number: '+91-9876543210', postal_code: '440001', is_verified: true, name: 'Aarav Sharma' },
  { user_id: 'u2', phone_number: '+91-9876543211', postal_code: '440002', is_verified: true, name: 'Priya Deshmukh' },
  { user_id: 'u3', phone_number: '+91-9876543212', postal_code: '440010', is_verified: false, name: 'Rohan Gupta' },
  { user_id: 'u4', phone_number: '+91-9876543213', postal_code: '440001', is_verified: true, name: 'Sneha Patil' },
  { user_id: 'u5', phone_number: '+91-9876543214', postal_code: '440003', is_verified: true, name: 'Vikram Joshi' },
];

export const ISSUE_CATEGORIES = [
  'Roads & Transport',
  'Water Supply',
  'Sanitation',
  'Street Lighting',
  'Parks & Recreation',
  'Drainage',
  'Public Safety',
  'Education',
  'Healthcare',
  'Other',
];

export const ISSUE_STATUSES = ['Proposed', 'Funded', 'In Progress', 'Resolved'];

export const MOCK_ISSUES = [
  {
    issue_id: 'iss-001',
    author_id: 'u1',
    author_name: 'Aarav Sharma',
    raw_text: 'Massive pothole on Wardha Road near Ajni Square causing accidents daily. Multiple vehicles damaged.',
    ai_category: 'Roads & Transport',
    severity_score: 5,
    status: 'In Progress',
    lat_lng: { lat: 21.1458, lng: 79.0882 },
    location_text: 'Wardha Road, Ajni Square',
    vote_count: 234,
    priority_score: (234 * 1.5) + (5 * 2) - (45 * 0.5),
    created_at: '2025-05-20T08:30:00Z',
    days_open: 45,
    similar_count: 12,
    updates: [
      { status: 'Proposed', date: '2025-05-20', note: 'Issue reported by citizen' },
      { status: 'Funded', date: '2025-06-01', note: 'Budget allocated: ₹2,50,000' },
      { status: 'In Progress', date: '2025-06-15', note: 'NMC road repair crew deployed' },
    ],
  },
  {
    issue_id: 'iss-002',
    author_id: 'u2',
    author_name: 'Priya Deshmukh',
    raw_text: 'No water supply in Dharampeth area for 3 consecutive days. Residents forced to buy tanker water.',
    ai_category: 'Water Supply',
    severity_score: 5,
    status: 'Funded',
    lat_lng: { lat: 21.1497, lng: 79.0806 },
    location_text: 'Dharampeth, Ward 23',
    vote_count: 189,
    priority_score: (189 * 1.5) + (5 * 2) - (30 * 0.5),
    created_at: '2025-06-04T10:15:00Z',
    days_open: 30,
    similar_count: 8,
    updates: [
      { status: 'Proposed', date: '2025-06-04', note: 'Water crisis reported' },
      { status: 'Funded', date: '2025-06-20', note: 'Emergency fund released: ₹5,00,000' },
    ],
  },
  {
    issue_id: 'iss-003',
    author_id: 'u4',
    author_name: 'Sneha Patil',
    raw_text: 'Street lights non-functional in entire stretch of Sadar area. Women feel unsafe walking at night.',
    ai_category: 'Street Lighting',
    severity_score: 4,
    status: 'Proposed',
    lat_lng: { lat: 21.1537, lng: 79.0815 },
    location_text: 'Sadar, Central Nagpur',
    vote_count: 156,
    priority_score: (156 * 1.5) + (4 * 2) - (20 * 0.5),
    created_at: '2025-06-14T14:20:00Z',
    days_open: 20,
    similar_count: 5,
    updates: [
      { status: 'Proposed', date: '2025-06-14', note: 'Street light complaint filed' },
    ],
  },
  {
    issue_id: 'iss-004',
    author_id: 'u5',
    author_name: 'Vikram Joshi',
    raw_text: 'Open drainage near Hanuman Nagar school creating health hazard for children. Foul smell and mosquito breeding.',
    ai_category: 'Drainage',
    severity_score: 5,
    status: 'Proposed',
    lat_lng: { lat: 21.1320, lng: 79.0756 },
    location_text: 'Hanuman Nagar, Near School',
    vote_count: 198,
    priority_score: (198 * 1.5) + (5 * 2) - (25 * 0.5),
    created_at: '2025-06-09T09:00:00Z',
    days_open: 25,
    similar_count: 6,
    updates: [
      { status: 'Proposed', date: '2025-06-09', note: 'Drainage issue reported' },
    ],
  },
  {
    issue_id: 'iss-005',
    author_id: 'u1',
    author_name: 'Aarav Sharma',
    raw_text: 'Broken park bench and damaged swings in Futala Lake park. Children cannot play safely.',
    ai_category: 'Parks & Recreation',
    severity_score: 1,
    status: 'Resolved',
    lat_lng: { lat: 21.1565, lng: 79.0452 },
    location_text: 'Futala Lake Park',
    vote_count: 45,
    priority_score: (45 * 1.5) + (1 * 2) - (60 * 0.5),
    created_at: '2025-05-05T11:30:00Z',
    days_open: 60,
    similar_count: 2,
    updates: [
      { status: 'Proposed', date: '2025-05-05', note: 'Park maintenance request filed' },
      { status: 'Funded', date: '2025-05-15', note: 'Budget allocated: ₹75,000' },
      { status: 'In Progress', date: '2025-05-25', note: 'Contractor assigned' },
      { status: 'Resolved', date: '2025-06-20', note: 'New benches and swings installed' },
    ],
  },
  {
    issue_id: 'iss-006',
    author_id: 'u2',
    author_name: 'Priya Deshmukh',
    raw_text: 'Garbage not collected in Laxmi Nagar for over a week. Piling up near residential buildings.',
    ai_category: 'Sanitation',
    severity_score: 4,
    status: 'In Progress',
    lat_lng: { lat: 21.1423, lng: 79.0910 },
    location_text: 'Laxmi Nagar, East Nagpur',
    vote_count: 132,
    priority_score: (132 * 1.5) + (4 * 2) - (15 * 0.5),
    created_at: '2025-06-19T07:45:00Z',
    days_open: 15,
    similar_count: 9,
    updates: [
      { status: 'Proposed', date: '2025-06-19', note: 'Sanitation complaint filed' },
      { status: 'In Progress', date: '2025-06-28', note: 'NMC sanitation team notified' },
    ],
  },
  {
    issue_id: 'iss-007',
    author_id: 'u4',
    author_name: 'Sneha Patil',
    raw_text: 'Government primary school roof leaking badly during monsoon. Classrooms unusable. 200+ students affected.',
    ai_category: 'Education',
    severity_score: 4,
    status: 'Funded',
    lat_lng: { lat: 21.1380, lng: 79.0680 },
    location_text: 'Manewada, South Nagpur',
    vote_count: 167,
    priority_score: (167 * 1.5) + (4 * 2) - (18 * 0.5),
    created_at: '2025-06-16T13:00:00Z',
    days_open: 18,
    similar_count: 3,
    updates: [
      { status: 'Proposed', date: '2025-06-16', note: 'School infrastructure complaint' },
      { status: 'Funded', date: '2025-06-30', note: 'Emergency repair fund: ₹3,00,000' },
    ],
  },
  {
    issue_id: 'iss-008',
    author_id: 'u5',
    author_name: 'Vikram Joshi',
    raw_text: 'No pedestrian crossing or speed breakers near Ambazari T-Point. Multiple accidents reported.',
    ai_category: 'Public Safety',
    severity_score: 5,
    status: 'Proposed',
    lat_lng: { lat: 21.1290, lng: 79.0530 },
    location_text: 'Ambazari T-Point',
    vote_count: 210,
    priority_score: (210 * 1.5) + (5 * 2) - (10 * 0.5),
    created_at: '2025-06-24T16:30:00Z',
    days_open: 10,
    similar_count: 4,
    updates: [
      { status: 'Proposed', date: '2025-06-24', note: 'Public safety issue reported' },
    ],
  },
  {
    issue_id: 'iss-009',
    author_id: 'u1',
    author_name: 'Aarav Sharma',
    raw_text: 'Primary health center in Nandanvan area has no doctor available after 2 PM. Patients turned away daily.',
    ai_category: 'Healthcare',
    severity_score: 4,
    status: 'Proposed',
    lat_lng: { lat: 21.1195, lng: 79.1020 },
    location_text: 'Nandanvan, East Nagpur',
    vote_count: 143,
    priority_score: (143 * 1.5) + (4 * 2) - (12 * 0.5),
    created_at: '2025-06-22T10:00:00Z',
    days_open: 12,
    similar_count: 2,
    updates: [
      { status: 'Proposed', date: '2025-06-22', note: 'Healthcare issue reported' },
    ],
  },
  {
    issue_id: 'iss-010',
    author_id: 'u2',
    author_name: 'Priya Deshmukh',
    raw_text: 'Major road cave-in near Sitabuldi metro station. Traffic diverted causing 2-hour delays.',
    ai_category: 'Roads & Transport',
    severity_score: 5,
    status: 'In Progress',
    lat_lng: { lat: 21.1466, lng: 79.0830 },
    location_text: 'Sitabuldi, Metro Station',
    vote_count: 312,
    priority_score: (312 * 1.5) + (5 * 2) - (5 * 0.5),
    created_at: '2025-06-29T06:00:00Z',
    days_open: 5,
    similar_count: 15,
    updates: [
      { status: 'Proposed', date: '2025-06-29', note: 'Road cave-in reported' },
      { status: 'Funded', date: '2025-06-30', note: 'Emergency fund: ₹10,00,000' },
      { status: 'In Progress', date: '2025-07-01', note: 'Metro authority repair team on site' },
    ],
  },
];

export const MOCK_TENDERS = [
  {
    tender_id: 't-001',
    portal_tender_id: 'GEM/2025/B/4521987',
    title: 'Supply and Installation of LED Street Lights — Nagpur Municipal Zone 3',
    department: 'Nagpur Municipal Corporation — Electrical Division',
    estimated_value: 4500000,
    deadline: '2025-07-15T17:00:00Z',
    portal_url: 'https://gem.gov.in/view_bid/4521987',
    source_portal: 'GEM',
    constituency: 'Nagpur West',
    status: 'Open',
    scraped_at: '2025-07-03T06:00:00Z',
    description: 'Procurement of 500 LED street lights (150W) with poles, wiring, and installation for Ward 23-28 areas including Dharampeth, Sadar, and Ramdaspeth.',
    category: 'Electrical Infrastructure',
  },
  {
    tender_id: 't-002',
    portal_tender_id: 'CPPP/NAG/2025/WS/0089',
    title: 'Repair & Maintenance of Water Supply Pipeline — Laxmi Nagar to Hanuman Nagar',
    department: 'Nagpur Municipal Corporation — Water Works',
    estimated_value: 12000000,
    deadline: '2025-07-20T17:00:00Z',
    portal_url: 'https://eprocure.gov.in/cppp/tender/0089',
    source_portal: 'CPPP',
    constituency: 'Nagpur East',
    status: 'Open',
    scraped_at: '2025-07-03T06:00:00Z',
    description: 'Complete overhaul of underground water supply pipeline from Laxmi Nagar distribution center to Hanuman Nagar. Includes pipe replacement, valve installation, and water meter fitting.',
    category: 'Water Infrastructure',
  },
  {
    tender_id: 't-003',
    portal_tender_id: 'MH-ePROC/2025/RD/1456',
    title: 'Road Resurfacing & Pothole Repair — Wardha Road (Ajni to Bardi)',
    department: 'Public Works Department — Nagpur Division',
    estimated_value: 25000000,
    deadline: '2025-07-25T17:00:00Z',
    portal_url: 'https://mahatenders.gov.in/tender/1456',
    source_portal: 'State eProcure',
    constituency: 'Nagpur South',
    status: 'Open',
    scraped_at: '2025-07-03T06:00:00Z',
    description: 'Resurfacing of 8.5 km stretch of Wardha Road from Ajni Square to Bardi. Includes pothole repair, lane marking, speed breaker installation, and drainage improvement.',
    category: 'Road Infrastructure',
  },
  {
    tender_id: 't-004',
    portal_tender_id: 'GEM/2025/S/7890123',
    title: 'Construction of Public Toilets — 15 Locations Across Nagpur',
    department: 'Nagpur Municipal Corporation — Health Division',
    estimated_value: 8000000,
    deadline: '2025-07-10T17:00:00Z',
    portal_url: 'https://gem.gov.in/view_bid/7890123',
    source_portal: 'GEM',
    constituency: 'Nagpur Central',
    status: 'Closed',
    scraped_at: '2025-07-02T12:00:00Z',
    description: 'Design, construction, and commissioning of 15 prefabricated public toilet blocks with water supply and sewage connection under Swachh Bharat Mission.',
    category: 'Sanitation',
  },
  {
    tender_id: 't-005',
    portal_tender_id: 'CPPP/NAG/2025/ED/0234',
    title: 'Renovation of Government Schools — South Nagpur Zone',
    department: 'Education Department — Nagpur District',
    estimated_value: 15000000,
    deadline: '2025-08-01T17:00:00Z',
    portal_url: 'https://eprocure.gov.in/cppp/tender/0234',
    source_portal: 'CPPP',
    constituency: 'Nagpur South',
    status: 'Open',
    scraped_at: '2025-07-03T06:00:00Z',
    description: 'Structural renovation of 8 government primary schools including roof repair, classroom expansion, toilet construction, and boundary wall construction.',
    category: 'Education Infrastructure',
  },
  {
    tender_id: 't-006',
    portal_tender_id: 'MH-ePROC/2025/DR/0678',
    title: 'Storm Water Drainage System — Manewada & Nandanvan Area',
    department: 'Nagpur Municipal Corporation — Drainage Division',
    estimated_value: 35000000,
    deadline: '2025-08-10T17:00:00Z',
    portal_url: 'https://mahatenders.gov.in/tender/0678',
    source_portal: 'State eProcure',
    constituency: 'Nagpur South',
    status: 'Open',
    scraped_at: '2025-07-03T06:00:00Z',
    description: 'Construction of new storm water drainage network covering 12 km in Manewada and Nandanvan areas to prevent monsoon waterlogging.',
    category: 'Drainage Infrastructure',
  },
  {
    tender_id: 't-007',
    portal_tender_id: 'GEM/2025/B/5567890',
    title: 'CCTV Surveillance System — Major Intersections Nagpur',
    department: 'Nagpur Police Commissionerate',
    estimated_value: 18000000,
    deadline: '2025-07-30T17:00:00Z',
    portal_url: 'https://gem.gov.in/view_bid/5567890',
    source_portal: 'GEM',
    constituency: 'Nagpur Central',
    status: 'Open',
    scraped_at: '2025-07-03T06:00:00Z',
    description: 'Supply and installation of 200 CCTV cameras with AI-based analytics at 50 major intersections including Sitabuldi, Ambazari, Dharampeth, and Sadar areas.',
    category: 'Public Safety',
  },
  {
    tender_id: 't-008',
    portal_tender_id: 'CPPP/NAG/2025/HC/0456',
    title: 'Upgradation of Primary Health Centers — East Nagpur',
    department: 'Health Department — Nagpur District',
    estimated_value: 22000000,
    deadline: '2025-08-15T17:00:00Z',
    portal_url: 'https://eprocure.gov.in/cppp/tender/0456',
    source_portal: 'CPPP',
    constituency: 'Nagpur East',
    status: 'Open',
    scraped_at: '2025-07-03T06:00:00Z',
    description: 'Complete upgradation of 5 primary health centers in East Nagpur including equipment procurement, building renovation, and staff quarters construction.',
    category: 'Healthcare Infrastructure',
  },
];

export const STATS = {
  totalIssues: 1247,
  resolvedIssues: 389,
  activeCitizens: 8543,
  tendersTracked: 156,
  fundsAllocated: 45000000,
  constituencies: 12,
};

export const SEVERITY_LABELS = {
  1: 'Minor',
  2: 'Low',
  3: 'Moderate',
  4: 'High',
  5: 'Critical',
};

export const SEVERITY_COLORS = {
  1: '#6ee7b7',
  2: '#86efac',
  3: '#fbbf24',
  4: '#f97316',
  5: '#ef4444',
};

export const STATUS_COLORS = {
  'Proposed': '#8b5cf6',
  'Funded': '#3b82f6',
  'In Progress': '#f59e0b',
  'Resolved': '#10b981',
  'Open': '#10b981',
  'Closed': '#6b7280',
};

export const PORTAL_COLORS = {
  'GEM': '#6366f1',
  'CPPP': '#ec4899',
  'State eProcure': '#14b8a6',
};

export function formatCurrency(value) {
  if (value >= 10000000) return `₹${(value / 10000000).toFixed(1)} Cr`;
  if (value >= 100000) return `₹${(value / 100000).toFixed(1)} L`;
  return `₹${value.toLocaleString('en-IN')}`;
}

export function formatDate(dateStr) {
  return new Date(dateStr).toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

export function daysUntil(dateStr) {
  const diff = new Date(dateStr) - new Date();
  return Math.max(0, Math.ceil(diff / (1000 * 60 * 60 * 24)));
}

export function calculatePriorityScore(votes, severity, daysOpen) {
  return (votes * 1.5) + (severity * 2) - (daysOpen * 0.5);
}
